# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3ef2015fd11c837f009552ab7d40082318fa944a4f2f1c6b8f9e41a0c9a6776dcab1826ba73ff5b315ad72e937d7f5c9516b321d17628352fc41769ced54d27

test:
  secret_key_base: 34dd2e20dffd82e6073646c9175045be84a600e65591a78694188885a39c038ca73e61a000626a558bd83b6c79b484fcd3a39b695078f05bc34cae11ddcf3e06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
